Dialog#main
{
    title:"${refresh_address}"
    layout:VBoxLayout
    w:550
    h:300

    GridLayout{
        column:2
        "${page_url}:" LineView#page_url{name:page_url}
        "${keyword}:" LineView{name:resid,css:"font-weight:bold;color:blue"}
    }
    
    TextEdit#address{
        name:address
    }
    TextEdit{
        viewonly:true
        stretch:min
        css:"color:gray"
        "${refresh_address_notice_}"
    }
    HBoxLayout
    {
        CheckBox#no_refresh_address_dialog{
            text:"${dont_show_this_again}"
        }
        <==>
        Button#copy
        {
            text:"${copy_address}"
            icon:"icons/16/copy.svg"
            click:{
                $copy(${#address})
                $close{#main}()
            }
        }
        Button#open{
            text:"${open_browser}"
            icon:"icons/16/web.svg"
            click:{
                $open-url(${#address})
                $close{#main}()
            }
        }
        Button{
            text:"${close}"
            click:$close{#main}()
        }
    }
} 
