config.load_autoconfig()

c.colors.tabs.bar.bg            = "#000000"
c.colors.tabs.even.bg           = "#000000"
c.colors.tabs.even.fg           = "#ffffff"
c.colors.tabs.odd.bg            = "#000000"
c.colors.tabs.odd.fg            = "#ffffff"
c.colors.tabs.selected.even.bg  = "#efe100"
c.colors.tabs.selected.odd.bg   = "#efe100"
c.colors.tabs.selected.even.fg  = "#000000"
c.colors.tabs.selected.odd.fg   = "#000000"
c.fonts.default_family          = "GohuFont 11 Nerd Font"
c.fonts.default_size            = "12pt"
c.tabs.position                 = "bottom"
c.tabs.title.alignment          = "center"
c.url.default_page              = "https://qutebrowser.org/"
c.url.start_pages               = "https://qutebrowser.org/"
c.window.title_format           = "{perc}{current_title}"
