return( {

    -- Drupal Modules
    { enabled = true,   name = 'drupal',                    'jdrupal-dev/drupal.nvim' },
    { enabled = true,   name = 'drupal-sh',                 'everynameistaken1/nvim-drupal-sh' },

    -- Vim Modules
    { enabled = false,  name = 'vim-gitgutter',             'airblade/vim-gitgutter' },
    { enabled = false,  name = 'vim-sleuth',                'tpope/vim-sleuth' },
    { enabled = false,  name = 'vim-visual-multi',          'mg979/vim-visual-multi' },

    -- Contrib Modules
    { enabled = true,	name = 'ale',                       'dense-analysis/ale' },
	{ enabled = false,	name = 'barbar',					'romgrk/barbar.nvim' },
	{ enabled = true,   name = 'blame',                     'FabijanZulj/blame.nvim' },
	{ enabled = false,	name = 'bufferline',				'akinsho/bufferline.nvim' },
	{ enabled = true,   name = 'colorizer',                 'norcalli/nvim-colorizer.lua' },
    { enabled = true,   name = 'commander',                 'FeiyouG/commander.nvim' },
	{ enabled = false,	name = 'ctrlspace',					'vim-ctrlspace/vim-ctrlspace' },
	{ enabled = true,	name = 'dap',                       'mfussenegger/nvim-dap' },
    { enabled = true,	name = 'dap-ui',                    'rcarriga/nvim-dap-ui' },
    { enabled = true,   name = 'diffview',                  'sindrets/diffview.nvim' },
    { enabled = true,   name = 'distant',                   'chipsenkbeil/distant.nvim' },
    { enabled = true,   name = 'dressing',                  'stevearc/dressing.nvim' },
    { enabled = true,   name = 'edgy',                      'folke/edgy.nvim' },
    { enabled = true,   name = 'emmet',                     'olrtg/nvim-emmet' },
    { enabled = true,	name = 'flash',                     'folke/flash.nvim' },
    { enabled = true,   name = 'git-signs',                 'lewis6991/gitsigns.nvim' },
    { enabled = true,   name = 'harpoon',                   'ThePrimeagen/harpoon' },
    { enabled = true,   name = 'history',                   'wilfreddenton/history.nvim' },
    { enabled = true,	name = 'lazydev',                   'folke/lazydev.nvim' },
    { enabled = true,   name = 'lazygit',                   'kdheepak/lazygit.nvim' },
    { enabled = false,	name = 'legendary',                 'mrjones2014/legendary.nvim' },
    { enabled = true,   name = 'lua-rocks',                 'vhyrro/luarocks.nvim' },
	{ enabled = false,	name = 'lualine',					'nvim-lualine/lualine.nvim' },
	{ enabled = false,  name = 'mapx',                      'b0o/mapx.nvim' },
    { enabled = true,   name = 'markdown',                  'MeanderingProgrammer/render-markdown.nvim' },
    { enabled = true,   name = 'markdown-preview',          'iamcco/markdown-preview.nvim' },
    { enabled = true,   name = 'marks',                     'chentoast/marks.nvim' },
    { enabled = true,   name = 'neominimap',                'Isrothy/neominimap.nvim' },
    { enabled = true,   name = 'mkdnflow',                  'jakewvincent/mkdnflow.nvim' },
    { enabled = false,  name = 'multicursor',               'jake-stewart/multicursor.nvim' },
    { enabled = true,   name = 'namespace',                 'ccaglak/namespace.nvim' },
    { enabled = false,	name = 'navigator',                 'numToStr/Navigator.nvim' },
    { enabled = true,   name = 'neoclip',                   'AckslD/nvim-neoclip.lua' },
    { enabled = false,	name = 'neodev',                    'folke/neodev.nvim' },
    { enabled = true,   name = 'neogit',                    'NeogitOrg/neogit' },
    { enabled = true,   name = 'neoscroll',                 'karb94/neoscroll.nvim' },
    { enabled = true,   name = 'noice',                     'folke/noice.nvim' },
    { enabled = true,   name = 'notify',                    'rcarriga/nvim-notify' },
    { enabled = true,   name = 'nterm',                     'jlesquembre/nterm.nvim' },
    { enabled = true,   name = 'nui-components',            'grapp-dev/nui-components.nvim' },
    { enabled = true,   name = 'overseer',                  'stevearc/overseer.nvim' },
    { enabled = false,  name = 'pane-resizer',              'mboyov/pane-resizer.nvim' },
    { enabled = false,  name = 'popui',                     'hood/popui.nvim' },
    { enabled = false,  name = 'precognition',              'tris203/precognition.nvim' },
    { enabled = false,  name = 'project',                   'ahmedkhalf/project.nvim' },
    { enabled = true,   name = 'rainbow-delimiters',        'HiPhish/rainbow-delimiters.nvim' },
    { enabled = true,   name = 'renamer',                   'filipdutescu/renamer.nvim' },
    { enabled = true,   name = 'scope',                     'tiagovla/scope.nvim' },
    { enabled = true,   name = 'scratch',                   'LintaoAmons/scratch.nvim' },
    { enabled = true,   name = 'scrollview',                'dstein64/nvim-scrollview' },
    { enabled = true,   name = 'stylus',                    'ChiliConSql/neovim-stylus' },
    { enabled = true,   name = 'surround',                  'kylechui/nvim-surround' },
	{ enabled = false,	name = 'tabby',						'nanozuki/tabby.nvim' },
    { enabled = true,	name = 'telescope',                 'nvim-telescope/telescope.nvim' },
    { enabled = true,   name = 'telescope-file-browser',    'nvim-telescope/telescope-file-browser.nvim' },
    { enabled = true,   name = 'telescope-scope',           'HUAHUAI23/telescope-session.nvim' },
    { enabled = true,   name = 'telescope-ui-select',       'nvim-telescope/telescope-ui-select.nvim' },
    { enabled = true,   name = 'tree',                      'nvim-tree/nvim-tree.lua' },
    { enabled = true,   name = 'treesitter',                'nvim-treesitter/nvim-treesitter' },
    { enabled = true,   name = 'treesj',                    'Wansmer/treesj' },
    { enabled = true,   name = 'trouble',                   'folke/trouble.nvim' },
    { enabled = true,   name = 'undotree',                  'jiaoshijie/undotree' },
    { enabled = true,   name = 'vgit',                      'tanvirtin/vgit.nvim' },
    { enabled = false, 	name = 'which-key',                 'folke/which-key.nvim' },
    { enabled = false,  name = 'yabs',                      'shadowofseaice/yabs.nvim' },

} )
