[Audio]
ReplayGain=album
Volume=100

[General]
AccuratePreviewThumbnail=true
AppendVideoToSingleInstance=true
ColorScheme=A Mole Like Ed
FooterStyle=floating
FullscreenOnStartUp=true
GuiStyle=Darkly
LastPlayedFile=file:///home/mikepadiernos/Library/Music/__ Unsorted/music-uploads/Radio Ga Ga(1).mp3
RememberWindowGeometry=true
ShowPreviewThumbnail=true
ShowTaskbarProgress=true
UseSingleInstance=true

[Playback]
RestoreFilePosition=true
SkipChapters=true

[Playlist]
CanToggleWithMouse=false
RememberState=true
Visible=true

[Subtitles]
AllowOnBlackBorders=true

[Video]
ScreenshotFormat=webp
