[Unified]
source                 = notmuch://~/Library/.library/.maildir
maildir-store          = ~/Library/.library/.maildir
maildir-account-path   = unified
query-map              = ~/.config/aerc/query-map.conf
default                = Unified Inbox
folders                = Unified Inbox,Unread,Today,Primary,Gmail,Outlook
folders-sort           = Unified Inbox,Unread,Today,Primary,Gmail,Outlook
check-mail             = 5m
check-mail-cmd         = ~/.config/aerc/scripts/unified-inbox.sh
check-mail-timeout     = 3m
exclude-tags           = trash,spam,deleted
from                   = Mike Padiernos <mike@padiernos.me>
outgoing               = smtp://mike%40padiernos.me@mail.padiernos.me
outgoing-cred-cmd      = PASSWORD_STORE_DIR="$HOME/.pass" pass mail/mike@padiernos.me | sed -n '1p'
cache-headers          = true

[mike@padiernos.me]
source        = maildir://~/Library/.library/.maildir/mike@padiernos.me
outgoing      = smtp://mike%40padiernos.me@mail.padiernos.me
outgoing-cred-cmd = PASSWORD_STORE_DIR="$HOME/.pass" pass mail/mike@padiernos.me | sed -n '1p'
default       = INBOX
from          = Mike Padiernos <mike@padiernos.me>
cache-headers = true
check-mail    = 5m
check-mail-cmd = mbsync -c ~/.mbsyncrc mike@padiernos.me
check-mail-timeout = 3m
folders       = INBOX,Notes,Drafts,Sent,Archives,Spam,Virus,Trash
folders-sort  = INBOX,Notes,Drafts,Sent,Archives,Spam,Virus,Trash
Archive       = Archives*

[mike.padiernos@gmail.com]
source        = maildir://~/Library/.library/.maildir/mike.padiernos@gmail.com
outgoing      = smtp://mike.padiernos%40gmail.com@smtp.gmail.com:587
outgoing-cred-cmd = PASSWORD_STORE_DIR="$HOME/.pass" pass mail/mike.padiernos@gmail.com | sed -n '1p'
default       = INBOX
from          = Mike Padiernos <mike.padiernos@gmail.com>
cache-headers = true
check-mail    = 5m
check-mail-cmd = mbsync -c ~/.mbsyncrc mike.padiernos@gmail.com
check-mail-timeout = 3m

[mike.padiernos@outlook.com]
source        = maildir://~/Library/.library/.maildir/mike.padiernos@outlook.com
outgoing      = smtp://mike.padiernos%40outlook.com@smtp-mail.outlook.com:587
outgoing-cred-cmd = PASSWORD_STORE_DIR="$HOME/.pass" pass mail/mike.padiernos@outlook.com | sed -n '1p'
default       = INBOX
from          = Mike Padiernos <mike.padiernos@outlook.com>
cache-headers = true
check-mail    = 5m
check-mail-cmd = mbsync -c ~/.mbsyncrc mike.padiernos@outlook.com
check-mail-timeout = 3m
