# Unified, cross-account notmuch folders for aerc.
Inbox=tag:inbox and not tag:trash and not tag:spam and not tag:deleted
Unread=tag:unread and tag:inbox and not tag:trash and not tag:spam and not tag:deleted
Today=date:today.. and tag:inbox and not tag:trash and not tag:spam and not tag:deleted
Sent=tag:sent and not tag:trash and not tag:spam and not tag:deleted
Drafts=tag:draft and not tag:trash and not tag:spam and not tag:deleted
Spam=tag:spam and not tag:trash and not tag:deleted
Archive=tag:archive and not tag:trash and not tag:spam and not tag:deleted
# mike@padiernos.me=path:**/mike@padiernos.me/** and tag:inbox and not tag:trash and not tag:spam and not tag:deleted
# mike.padiernos@gmail.com=path:**/mike.padiernos@gmail.com/** and tag:inbox and not tag:trash and not tag:spam and not tag:deleted
# mike.padiernos@outlook.com=path:**/mike.padiernos@outlook.com/** and tag:inbox and not tag:trash and not tag:spam and not tag:deleted