# Unified, cross-account notmuch folders for aerc.
Unified Inbox=tag:inbox and not tag:trash and not tag:spam and not tag:deleted
Unread=tag:unread and tag:inbox and not tag:trash and not tag:spam and not tag:deleted
Today=date:today.. and tag:inbox and not tag:trash and not tag:spam and not tag:deleted
Primary=path:**/mike@padiernos.me/** and tag:inbox and not tag:trash and not tag:spam and not tag:deleted
Gmail=path:**/mike.padiernos@gmail.com/** and tag:inbox and not tag:trash and not tag:spam and not tag:deleted
Outlook=path:**/mike.padiernos@outlook.com/** and tag:inbox and not tag:trash and not tag:spam and not tag:deleted